# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/oriole/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oriole)

$(call add-radio-file-sha1-checked,radio/abl.img,cbbcd2196abdff20b5a513c73d298cdd9b79ef62)
$(call add-radio-file-sha1-checked,radio/bl1.img,8215820e95ea582fda5026cc04d27d85f7c3eb12)
$(call add-radio-file-sha1-checked,radio/bl2.img,e39bef9183cc14794977a188835d1353b75584d8)
$(call add-radio-file-sha1-checked,radio/bl31.img,a1a7d86c5286beeea1cecdac906086d55c6a82fd)
$(call add-radio-file-sha1-checked,radio/gsa.img,e5c6813ff5d595235b996b5c0bc370de0ff9d400)
$(call add-radio-file-sha1-checked,radio/ldfw.img,59d33bca00cacae5cd92d516c55db4e440136875)
$(call add-radio-file-sha1-checked,radio/modem.img,9cf7aba4ca589db112b3e2e19c485969eb248c09)
$(call add-radio-file-sha1-checked,radio/pbl.img,a039aeed7c71fe1d1c3679777a55c1959524dd11)
$(call add-radio-file-sha1-checked,radio/tzsw.img,f2579d2e4f573dd88f9c972fd08c8fc6b7f76f3f)

endif
