# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/oriole/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    bl1 \
    bl2 \
    bl31 \
    gsa \
    ldfw \
    modem \
    pbl \
    tzsw
